import React from "react";

function BeforeAfter({ status }) {
  const isBlocked = status === "blocked";
  
  // If the status is safe, the comparison isn't as dramatic, but we still show it to illustrate protection logic
  const leftIcon = isBlocked ? "❌" : "⚠️";
  const rightIcon = isBlocked ? "✅" : "✅";

  const leftItems = isBlocked 
    ? [
        "Biased decision generated by model",
        "Decision immediately delivered to user",
        "Harm perpetuated at scale"
      ]
    : [
        "Decisions generated blindly",
        "No continuous fairness telemetry",
        "Vulnerable to latent drift over time"
      ];

  const rightItems = isBlocked
    ? [
        "Real-time interception of anomaly",
        "Discriminatory decision actively blocked",
        "Harm prevented from reaching user"
      ]
    : [
        "Continuous fairness telemetry active",
        "Decisions analyzed in micro-batches",
        "System authorized to proceed safely"
      ];

  // Colors match the current live status
  const rightBg = isBlocked ? "bg-emerald-50 border-emerald-300" : "bg-emerald-50 border-emerald-300";
  const rightTextColor = "text-emerald-700";
  const rightCheck = "text-emerald-500";

  return (
    <div className="w-full mb-8 animate-reveal-up delay-[200ms]">
      <h3 className="text-xs font-black uppercase tracking-widest text-slate-500 mb-4 ml-1">Impact Comparison</h3>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* WITHOUT FAIRWATCH */}
        <div className="elite-panel bg-slate-50 border border-slate-200 p-8 shadow-sm">
           <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-200">
              <span className="text-3xl">{leftIcon}</span>
              <h3 className="font-bold text-slate-800 text-lg uppercase tracking-wide">Legacy System (No Protection)</h3>
           </div>
           <ul className="space-y-4 text-base font-medium text-slate-600">
             {leftItems.map((item, idx) => (
                <li key={idx} className="flex gap-3">
                  <span className="text-slate-400 font-bold">•</span>
                  <span>{item}</span>
                </li>
             ))}
           </ul>
        </div>

        {/* WITH FAIRWATCH */}
        <div className={`elite-panel p-8 shadow-md border ${rightBg}`}>
           <div className="flex items-center gap-3 mb-6 pb-4 border-b border-emerald-200/50">
              <span className="text-3xl">{rightIcon}</span>
              <h3 className="font-bold text-emerald-900 text-lg uppercase tracking-wide">Protected System (FairWatch)</h3>
           </div>
           <ul className={`space-y-4 text-base font-bold ${rightTextColor}`}>
             {rightItems.map((item, idx) => (
                <li key={idx} className="flex gap-3">
                  <span className={`font-black ${rightCheck}`}>✔</span>
                  <span>{item}</span>
                </li>
             ))}
           </ul>
        </div>

      </div>
    </div>
  );
}

export default BeforeAfter;
